ERROR - 2023-02-13 22:43:05 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2023-02-13 22:43:05 --> Unable to connect to the database.
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(76): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#2 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(91): App\Controllers\Login->validar_login(NULL)
#3 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(935): App\Controllers\Login->index()
#4 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-13 22:43:05 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in /home/meuruca/api.meuruca.ao/app/Views/errors/html/error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', '/home/meuruca/a...', 100, Array)
#1 /home/meuruca/api.meuruca.ao/app/Views/errors/html/error_exception.php(100): print_r(Object(App\Controllers\Login), true)
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/Debug/Exceptions.php(281): include('/home/meuruca/a...')
#3 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/Debug/Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2023-02-13 22:50:52 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2023-02-13 22:50:52 --> Unable to connect to the database.
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(76): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#2 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(91): App\Controllers\Login->validar_login(NULL)
#3 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(935): App\Controllers\Login->index()
#4 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2023-02-13 22:51:54 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2023-02-13 22:51:54 --> Unable to connect to the database.
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(76): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#2 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(91): App\Controllers\Login->validar_login(NULL)
#3 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(935): App\Controllers\Login->index()
#4 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2023-02-13 22:52:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2023-02-13 22:52:18 --> Unable to connect to the database.
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(76): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#2 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(91): App\Controllers\Login->validar_login(NULL)
#3 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(935): App\Controllers\Login->index()
#4 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2023-02-13 22:55:31 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2023-02-13 22:55:31 --> Unable to connect to the database.
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(76): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#2 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(91): App\Controllers\Login->validar_login(NULL)
#3 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(935): App\Controllers\Login->index()
#4 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2023-02-13 22:58:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2023-02-13 22:58:18 --> Unable to connect to the database.
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(76): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#2 /home/meuruca/api.meuruca.ao/app/Controllers/Login.php(91): App\Controllers\Login->validar_login(NULL)
#3 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(935): App\Controllers\Login->index()
#4 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-13 23:33:26 --> Class 'App\Models\LojaModel' not found
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(907): App\Controllers\Operations->__construct()
#1 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-02-13 23:34:07 --> Class 'App\Models\LojaModel' not found
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(907): App\Controllers\Operations->__construct()
#1 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-02-13 23:34:37 --> Class 'App\Models\LojaModel' not found
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(907): App\Controllers\Operations->__construct()
#1 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-02-13 23:36:30 --> Class 'App\Models\LojaModel' not found
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(907): App\Controllers\Operations->__construct()
#1 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-02-13 23:36:30 --> Class 'App\Models\LojaModel' not found
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(907): App\Controllers\Operations->__construct()
#1 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-02-13 23:36:52 --> Class 'App\Models\LojaModel' not found
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(907): App\Controllers\Operations->__construct()
#1 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-02-13 23:39:17 --> Class 'App\Models\LojaModel' not found
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(907): App\Controllers\Operations->__construct()
#1 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-02-13 23:39:30 --> Class 'App\Models\LojaModel' not found
#0 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(907): App\Controllers\Operations->__construct()
#1 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#2 /home/meuruca/api.meuruca.ao/vendor/codeigniter4/framework/system/CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/meuruca/api.meuruca.ao/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
