CRITICAL - 2022-03-31 05:51:04 --> Call to undefined method App\Controllers\Operations::getUserCars()
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Gestaoviatura->index()
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestaoviatura))
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#5 {main}
CRITICAL - 2022-03-31 06:31:33 --> Undefined index: id
#0 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(158): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\WORKPLACE\\me...', 158, Array)
#1 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(108): App\Controllers\Operations->newuser(Object(App\Models\UtilizadorModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#7 {main}
CRITICAL - 2022-03-31 06:31:47 --> Undefined index: id
#0 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(158): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\WORKPLACE\\me...', 158, Array)
#1 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(108): App\Controllers\Operations->newuser(Object(App\Models\UtilizadorModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#7 {main}
CRITICAL - 2022-03-31 06:31:50 --> Undefined index: id
#0 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(158): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\WORKPLACE\\me...', 158, Array)
#1 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(108): App\Controllers\Operations->newuser(Object(App\Models\UtilizadorModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#7 {main}
CRITICAL - 2022-03-31 07:20:44 --> Array to string conversion
#0 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(139): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\WORKPLACE\\me...', 139, Array)
#1 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->pesquisar(Object(App\Models\ProprietarioModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#7 {main}
CRITICAL - 2022-03-31 07:26:47 --> Call to undefined method App\Controllers\Operations::pesquisar()
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#5 {main}
ERROR - 2022-03-31 07:28:14 --> mysqli_sql_exception: Unknown column 'modelo' in 'where clause' in C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(139): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->searcheCar('q', Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\ProprietarioModel))
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
CRITICAL - 2022-03-31 07:28:14 --> Unknown column 'modelo' in 'where clause'
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT * FROM p...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM p...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM p...')
#3 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(139): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->searcheCar('q', Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\ProprietarioModel))
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
ERROR - 2022-03-31 07:28:39 --> mysqli_sql_exception: Unknown column 'modelo' in 'where clause' in C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT * FROM v...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM v...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM v...')
#3 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(139): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->searcheCar('q', Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\ViaturaModel))
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
CRITICAL - 2022-03-31 07:28:39 --> Unknown column 'modelo' in 'where clause'
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT * FROM v...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM v...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM v...')
#3 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(139): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->searcheCar('q', Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\ViaturaModel))
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
ERROR - 2022-03-31 07:28:58 --> mysqli_sql_exception: Unknown column 'modelo' in 'where clause' in C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT * FROM v...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM v...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM v...')
#3 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(139): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->searcheCar('q', Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\ViaturaModel))
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
CRITICAL - 2022-03-31 07:28:58 --> Unknown column 'modelo' in 'where clause'
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT * FROM v...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM v...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM v...')
#3 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(139): CodeIgniter\Database\BaseConnection->query('SELECT * FROM v...')
#4 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->searcheCar('q', Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\ViaturaModel))
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
CRITICAL - 2022-03-31 07:37:42 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::limit()
#0 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->searcheCar('q', Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\ViaturaModel))
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#6 {main}
CRITICAL - 2022-03-31 07:40:30 --> Object of class App\Models\ViaturaModel could not be converted to string
#0 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(116): App\Controllers\Operations->searcheCar('q', Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\ViaturaModel))
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#6 {main}
CRITICAL - 2022-03-31 08:10:03 --> There is no data to insert.
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(735): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#3 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#4 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\ViaturaModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
ERROR - 2022-03-31 08:12:36 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`meuruca`.`viaturas`, CONSTRAINT `FK_viatura_2` FOREIGN KEY (`proprietario`) REFERENCES `proprietarios` (`id`)) in C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `vi...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `vi...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `vi...')
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vi...', Array, false)
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#9 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\ViaturaModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#10 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#11 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#12 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#15 {main}
CRITICAL - 2022-03-31 08:12:36 --> Cannot add or update a child row: a foreign key constraint fails (`meuruca`.`viaturas`, CONSTRAINT `FK_viatura_2` FOREIGN KEY (`proprietario`) REFERENCES `proprietarios` (`id`))
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `vi...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `vi...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `vi...')
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vi...', Array, false)
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#9 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\ViaturaModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#10 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#11 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#12 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#15 {main}
ERROR - 2022-03-31 08:13:08 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`meuruca`.`viaturas`, CONSTRAINT `FK_viatura_3` FOREIGN KEY (`ano`) REFERENCES `ano_fabricos` (`id`)) in C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `vi...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `vi...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `vi...')
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vi...', Array, false)
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#9 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\ViaturaModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#10 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#11 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#12 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#15 {main}
CRITICAL - 2022-03-31 08:13:08 --> Cannot add or update a child row: a foreign key constraint fails (`meuruca`.`viaturas`, CONSTRAINT `FK_viatura_3` FOREIGN KEY (`ano`) REFERENCES `ano_fabricos` (`id`))
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `vi...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `vi...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `vi...')
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `vi...', Array, false)
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#9 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\ViaturaModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#10 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#11 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#12 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#15 {main}
ERROR - 2022-03-31 08:15:18 --> mysqli_sql_exception: Table 'meuruca.modelomodels' doesn't exist in C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `modelom...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `modelom...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `modelom...')
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `modelom...', Array, false)
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(901): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(663): CodeIgniter\Model->update('1', Array)
#8 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#9 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\ModeloModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#10 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#11 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#12 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#15 {main}
CRITICAL - 2022-03-31 08:15:18 --> Table 'meuruca.modelomodels' doesn't exist
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `modelom...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `modelom...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `modelom...')
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `modelom...', Array, false)
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(901): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(663): CodeIgniter\Model->update('1', Array)
#8 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#9 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\ModeloModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#10 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#11 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#12 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#15 {main}
ERROR - 2022-03-31 08:16:39 --> mysqli_sql_exception: Unknown column 'ano' in 'field list' in C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `an...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#9 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\AnofabricoModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#10 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#11 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#12 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#15 {main}
CRITICAL - 2022-03-31 08:16:39 --> Unknown column 'ano' in 'field list'
#0 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `an...')
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\WORKPLACE\meuruca\app\Helpers\funcao_helper.php(16): CodeIgniter\BaseModel->save(Array)
#9 C:\WORKPLACE\meuruca\app\Controllers\Operations.php(92): cadastronormal(Object(App\Models\AnofabricoModel), Array, Object(CodeIgniter\Database\MySQLi\Connection), Object(App\Models\AuditoriaModel))
#10 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Operations->index()
#11 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operations))
#12 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#15 {main}
CRITICAL - 2022-03-31 09:36:54 --> Undefined variable: i
#0 C:\WORKPLACE\meuruca\app\Views\gestaoviatura\home.php(34): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\WORKPLACE\\me...', 34, Array)
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\WORKPLACE\\me...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('gestaoviatura/h...', Array, true)
#4 C:\WORKPLACE\meuruca\app\Controllers\Gestaoviatura.php(42): view('gestaoviatura/h...')
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Gestaoviatura->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestaoviatura))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
CRITICAL - 2022-03-31 19:34:17 --> Undefined variable: notificarioTitle
#0 C:\WORKPLACE\meuruca\app\Views\main\responsealert.php(37): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\WORKPLACE\\me...', 37, Array)
#1 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\WORKPLACE\\me...')
#2 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('main/responseal...', Array, true)
#4 C:\WORKPLACE\meuruca\app\Controllers\Login.php(176): view('main/responseal...')
#5 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(935): App\Controllers\Login->index()
#6 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#7 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\WORKPLACE\meuruca\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\WORKPLACE\meuruca\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKPLACE\\me...')
#10 {main}
